In [46]:
!pip install --trusted-host pypi.org ipython-sql

Requirement already satisfied: ipython-sql in c:\osgeo4~1\apps\python37\lib\site-packages (0.3.9)
Requirement already satisfied: prettytable in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (0.7.2)
Requirement already satisfied: ipython>=1.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (7.13.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: six in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (1.14.0)
Requirement already satisfied: sqlparse in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (0.3.1)
Requirement already satisfied: sqlalchemy>=0.6.7 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (1.3.16)
Requirement already satisfied: pickleshare in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (3.0.5)
Requirement already satisfied: backcall in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: setuptools>=18.5 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (45.2.0)
Requirement already satisfied: jedi>=0.10 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.17.0)
Requirement already satisfied: decorator in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (4.4.1)
Requirement already satisfied: pygments in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (2.5.2)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.4.3)
Requirement already satisfied: traitlets>=4.2 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (4.3.3)
Requirement already satisfied: wcwidth in c:\osgeo4~1\apps\python37\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.1.9)
Requirement already satisfied: parso>=0.7.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.7.0)

In [47]:
!pip install ipython-sql
!pip install sqlalchemy

Requirement already satisfied: ipython-sql in c:\osgeo4~1\apps\python37\lib\site-packages (0.3.9)
Requirement already satisfied: ipython-genutils>=0.1.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: prettytable in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (0.7.2)
Requirement already satisfied: ipython>=1.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (7.13.0)
Requirement already satisfied: six in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (1.14.0)
Requirement already satisfied: sqlparse in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (0.3.1)
Requirement already satisfied: sqlalchemy>=0.6.7 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython-sql) (1.3.16)
Requirement already satisfied: decorator in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (4.4.1)
Requirement already satisfied: backcall in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: pygments in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (2.5.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (3.0.5)
Requirement already satisfied: setuptools>=18.5 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (45.2.0)
Requirement already satisfied: traitlets>=4.2 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (4.3.3)
Requirement already satisfied: pickleshare in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.4.3)
Requirement already satisfied: jedi>=0.10 in c:\osgeo4~1\apps\python37\lib\site-packages (from ipython>=1.0->ipython-sql) (0.17.0)
Requirement already satisfied: wcwidth in c:\osgeo4~1\apps\python37\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.1.9)
Requirement already satisfied: parso>=0.7.0 in c:\osgeo4~1\apps\python37\lib\site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.7.0)
Requirement already satisfied: sqlalchemy in c:\osgeo4~1\apps\python37\lib\site-packages (1.3.16)

In [48]:
import pandas as pd
import psycopg2
import sqlalchemy
import matplotlib as plt

%matplotlib inline

In [49]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [50]:
from sqlalchemy import create_engine

In [51]:
# Example format
%sql postgresql://postgres:1234@localhost/postgres

'Connected: postgres@postgres'

In [52]:
# Example format
engine = create_engine('postgresql://postgres:1234@localhost/postgres')

In [57]:
%%sql

SELECT data_relatorio, suspeitos, confirmados, nao_confirmados, aguarda_resultados, recuperados, obitos, em_vigilancia, importados, internados
FROM situacao_epidemiologica

 * postgresql://postgres:***@localhost/postgres
55 rows affected.

[(datetime.date(2020, 3, 7), 224, 21, None, 47, None, 0, 412, 5, 21),
 (datetime.date(2020, 3, 8), 281, 30, None, 56, None, 0, 447, 6, 30),
 (datetime.date(2020, 3, 10), 375, 41, None, 83, None, 0, 667, 8, 40),
 (datetime.date(2020, 3, 13), 1308, 112, None, 172, None, 0, 5674, 33, 107),
 (datetime.date(2020, 3, 14), 1704, 169, None, 126, 1, 0, 5011, 39, 114),
 (datetime.date(2020, 3, 16), 2908, 331, 2203, 374, 3, 0, 4592, 47, 139),
 (datetime.date(2020, 3, 18), 5067, 642, 4074, 351, 3, 0, 6656, 62, 89),
 (datetime.date(2020, 3, 20), 7732, 1020, 5862, 850, 5, 0, 9008, 95, 126),
 (datetime.date(2020, 3, 21), 9854, 1280, 7515, 1059, 5, 0, 13155, 104, 156),
 (datetime.date(2020, 3, 31), 52086, 7443, 40033, 4610, 43, 160, 19260, None, 627),
 (datetime.date(2020, 3, 3), 101, 4, None, None, None, 0, None, 2, None),
 (datetime.date(2020, 4, 26), 236410, 23864, 207873, 4673, 1329, 903, 30453, 751, 1005),
 (datetime.date(2020, 4, 22), 210302, 21982, 185101, 3219, 1143, 785, 30646, 735, 1146),
 (datetime.date(2020, 4, 25), 231737, 23392, 203562, 4783, 1277, 880, 29932, 741, 1040),
 (datetime.date(2020, 3, 9), 339, 39, None, 67, None, 0, 496, 7, 38),
 (datetime.date(2020, 3, 11), 471, 59, None, 83, None, 0, 3066, 12, 57),
 (datetime.date(2020, 3, 12), 637, 78, None, 133, None, 0, 4923, 19, 69),
 (datetime.date(2020, 3, 15), 2271, 245, 1746, 281, 2, 0, 4592, 47, 139),
 (datetime.date(2020, 3, 17), 4030, 448, 3259, 323, 3, 0, 6852, 61, 206),
 (datetime.date(2020, 3, 27), 25431, 4268, 17168, 3995, 43, 76, 19816, 330, 354),
 (datetime.date(2020, 3, 28), 32754, 5170, 22646, 4938, 43, 100, 19927, 330, 418),
 (datetime.date(2020, 3, 29), 38042, 5962, 26572, 5508, 43, 119, 17785, 427, 486),
 (datetime.date(2020, 3, 30), 44206, 6408, 32953, 4845, 43, 140, 11482, 431, 571),
 (datetime.date(2020, 4, 4), 81087, 10524, 65045, 5518, 75, 266, 22858, 603, 1075),
 (datetime.date(2020, 4, 1), 59457, 8251, 46249, 4957, 43, 187, 20275, 523, 726),
 (datetime.date(2020, 4, 2), 66895, 9034, 52903, 4958, 68, 209, 21798, 550, 1042),
 (datetime.date(2020, 4, 3), 74377, 9886, 59099, 5392, 68, 246, 22556, 576, 1058),
 (datetime.date(2020, 4, 6), 91794, 11730, 75564, 4500, 140, 311, 23470, 623, 1099),
 (datetime.date(2020, 4, 7), 99730, 12442, 82846, 4442, 184, 345, 25070, 640, 1180),
 (datetime.date(2020, 4, 8), 104886, 13141, 85842, 5903, 196, 380, 24481, 637, 1211),
 (datetime.date(2020, 3, 4), 117, 6, None, None, None, 0, 81, 4, None),
 (datetime.date(2020, 3, 5), 147, 9, None, None, None, 0, 213, 5, 9),
 (datetime.date(2020, 3, 6), 181, 13, None, 30, None, 0, 354, 5, 13),
 (datetime.date(2020, 3, 26), 22257, 3544, 16718, 1995, 43, 60, 14994, 330, 191),
 (datetime.date(2020, 4, 5), 86370, 11278, 70130, 4962, 75, 295, 23209, 619, 1084),
 (datetime.date(2020, 4, 9), 115158, 13956, 97401, 3801, 205, 409, 24708, 642, 1173),
 (datetime.date(2020, 4, 10), 123564, 15472, 103583, 4509, 233, 435, 25914, 660, 1179),
 (datetime.date(2020, 4, 11), 130300, 15987, 110352, 3961, 266, 470, 25432, 660, 1175),
 (datetime.date(2020, 4, 12), 136243, 16585, 116047, 3611, 277, 504, 25041, 697, 1177),
 (datetime.date(2020, 4, 23), 219848, 22353, 193447, 4048, 1201, 820, 30342, 741, 1095),
 (datetime.date(2020, 3, 19), 6061, 785, 4788, 488, 3, 0, 8091, 68, 89),
 (datetime.date(2020, 3, 22), 11779, 1600, 9027, 1152, 5, 14, 12562, 114, 169),
 (datetime.date(2020, 3, 23), 13674, 2060, 10212, 1402, 14, 23, 11842, 142, 201),
 (datetime.date(2020, 3, 24), 15474, 2362, 11329, 1783, 22, 33, 11842, 142, 203),
 (datetime.date(2020, 3, 25), 21125, 2995, 16569, 1591, 22, 43, 13624, 155, 276),
 (datetime.date(2020, 4, 13), 139184, 16934, 118986, 3264, 277, 535, 26989, 707, 1187),
 (datetime.date(2020, 4, 14), 142514, 17448, 122592, 2474, 347, 567, 23265, 707, 1227),
 (datetime.date(2020, 4, 15), 150804, 18091, 128653, 4060, 383, 599, 26144, 723, 1200),
 (datetime.date(2020, 4, 16), 154727, 18841, 131976, 3910, 493, 629, 26065, 729, 1302),
 (datetime.date(2020, 4, 17), 158940, 19022, 135113, 4805, 519, 657, 25456, 731, 1284),
 (datetime.date(2020, 4, 18), 162711, 19685, 137860, 5166, 610, 687, 25456, 735, 1253),
 (datetime.date(2020, 4, 19), 187604, 20206, 162439, 4959, 610, 714, 27947, 735, 1243),
 (datetime.date(2020, 4, 20), 198353, 20863, 172751, 4739, 610, 735, 30805, 735, 1208),
 (datetime.date(2020, 4, 21), 202769, 21379, 176381, 5009, 917, 762, 30646, 735, 1172),
 (datetime.date(2020, 4, 24), 227393, 22797, 200219, 4377, 1228, 854, 29621, 741, 1068)]

In [59]:
dados = pd.read_sql('SELECT data_relatorio, suspeitos, confirmados, nao_confirmados, aguarda_resultados, recuperados, obitos, em_vigilancia, importados, internados FROM situacao_epidemiologica', engine)

dados

,data_relatorio,suspeitos,confirmados,nao_confirmados,aguarda_resultados,recuperados,obitos,em_vigilancia,importados,internados
0,2020-03-07,224,21,NaN,47.0,NaN,0,412.0,5.0,21.0
1,2020-03-08,281,30,NaN,56.0,NaN,0,447.0,6.0,30.0
2,2020-03-10,375,41,NaN,83.0,NaN,0,667.0,8.0,40.0
3,2020-03-13,1308,112,NaN,172.0,NaN,0,5674.0,33.0,107.0
4,2020-03-14,1704,169,NaN,126.0,1.0,0,5011.0,39.0,114.0
5,2020-03-16,2908,331,2203.0,374.0,3.0,0,4592.0,47.0,139.0
6,2020-03-18,5067,642,4074.0,351.0,3.0,0,6656.0,62.0,89.0
7,2020-03-20,7732,1020,5862.0,850.0,5.0,0,9008.0,95.0,126.0
8,2020-03-21,9854,1280,7515.0,1059.0,5.0,0,13155.0,104.0,156.0
9,2020-03-31,52086,7443,40033.0,4610.0,43.0,160,19260.0,NaN,627.0
10,2020-03-03,101,4,NaN,NaN,NaN,0,NaN,2.0,NaN
11,2020-04-26,236410,23864,207873.0,4673.0,1329.0,903,30453.0,751.0,1005.0
12,2020-04-22,210302,21982,185101.0,3219.0,1143.0,785,30646.0,735.0,1146.0
13,2020-04-25,231737,23392,203562.0,4783.0,1277.0,880,29932.0,741.0,1040.0
14,2020-03-09,339,39,NaN,67.0,NaN,0,496.0,7.0,38.0
15,2020-03-11,471,59,NaN,83.0,NaN,0,3066.0,12.0,57.0
16,2020-03-12,637,78,NaN,133.0,NaN,0,4923.0,19.0,69.0
17,2020-03-15,2271,245,1746.0,281.0,2.0,0,4592.0,47.0,139.0
18,2020-03-17,4030,448,3259.0,323.0,3.0,0,6852.0,61.0,206.0
19,2020-03-27,25431,4268,17168.0,3995.0,43.0,76,19816.0,330.0,354.0
20,2020-03-28,32754,5170,22646.0,4938.0,43.0,100,19927.0,330.0,418.0
21,2020-03-29,38042,5962,26572.0,5508.0,43.0,119,17785.0,427.0,486.0
22,2020-03-30,44206,6408,32953.0,4845.0,43.0,140,11482.0,431.0,571.0
23,2020-04-04,81087,10524,65045.0,5518.0,75.0,266,22858.0,603.0,1075.0
24,2020-04-01,59457,8251,46249.0,4957.0,43.0,187,20275.0,523.0,726.0
25,2020-04-02,66895,9034,52903.0,4958.0,68.0,209,21798.0,550.0,1042.0
26,2020-04-03,74377,9886,59099.0,5392.0,68.0,246,22556.0,576.0,1058.0
27,2020-04-06,91794,11730,75564.0,4500.0,140.0,311,23470.0,623.0,1099.0
28,2020-04-07,99730,12442,82846.0,4442.0,184.0,345,25070.0,640.0,1180.0
29,2020-04-08,104886,13141,85842.0,5903.0,196.0,380,24481.0,637.0,1211.0
30,2020-03-04,117,6,NaN,NaN,NaN,0,81.0,4.0,NaN
31,2020-03-05,147,9,NaN,NaN,NaN,0,213.0,5.0,9.0
32,2020-03-06,181,13,NaN,30.0,NaN,0,354.0,5.0,13.0
33,2020-03-26,22257,3544,16718.0,1995.0,43.0,60,14994.0,330.0,191.0
34,2020-04-05,86370,11278,70130.0,4962.0,75.0,295,23209.0,619.0,1084.0
35,2020-04-09,115158,13956,97401.0,3801.0,205.0,409,24708.0,642.0,1173.0
36,2020-04-10,123564,15472,103583.0,4509.0,233.0,435,25914.0,660.0,1179.0
37,2020-04-11,130300,15987,110352.0,3961.0,266.0,470,25432.0,660.0,1175.0
38,2020-04-12,136243,16585,116047.0,3611.0,277.0,504,25041.0,697.0,1177.0
39,2020-04-23,219848,22353,193447.0,4048.0,1201.0,820,30342.0,741.0,1095.0
40,2020-03-19,6061,785,4788.0,488.0,3.0,0,8091.0,68.0,89.0
41,2020-03-22,11779,1600,9027.0,1152.0,5.0,14,12562.0,114.0,169.0
42,2020-03-23,13674,2060,10212.0,1402.0,14.0,23,11842.0,142.0,201.0
43,2020-03-24,15474,2362,11329.0,1783.0,22.0,33,11842.0,142.0,203.0
44,2020-03-25,21125,2995,16569.0,1591.0,22.0,43,13624.0,155.0,276.0
45,2020-04-13,139184,16934,118986.0,3264.0,277.0,535,26989.0,707.0,1187.0
46,2020-04-14,142514,17448,122592.0,2474.0,347.0,567,23265.0,707.0,1227.0
47,2020-04-15,150804,18091,128653.0,4060.0,383.0,599,26144.0,723.0,1200.0
48,2020-04-16,154727,18841,131976.0,3910.0,493.0,629,26065.0,729.0,1302.0
49,2020-04-17,158940,19022,135113.0,4805.0,519.0,657,25456.0,731.0,1284.0
50,2020-04-18,162711,19685,137860.0,5166.0,610.0,687,25456.0,735.0,1253.0
51,2020-04-19,187604,20206,162439.0,4959.0,610.0,714,27947.0,735.0,1243.0
52,2020-04-20,198353,20863,172751.0,4739.0,610.0,735,30805.0,735.0,1208.0
53,2020-04-21,202769,21379,176381.0,5009.0,917.0,762,30646.0,735.0,1172.0
54,2020-04-24,227393,22797,200219.0,4377.0,1228.0,854,29621.0,741.0,1068.0